# This is a basic workflow to help you get started with Actions

name: release/minor

on: 
  workflow_dispatch:

jobs:
  sbt:
    name: sbt publish
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9
      - name: Publish
        if: github.event.pusher.name != 'GitHub Actions Bot'
        run: |-
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          sbt "versionBump minor"
          git add version.sbt
          git commit -m "Bump version"
          git push origin main
          sbt publish
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
